//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace WebService.Auto_Testing_Service {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RvOperationCompleted;
        
        private System.Threading.SendOrPostCallback ETL_RvOperationCompleted;
        
        private System.Threading.SendOrPostCallback TxOperationCompleted;
        
        private System.Threading.SendOrPostCallback ETL_TxOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WebService.Properties.Settings.Default.WebService_Auto_Testing_Service_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RvCompletedEventHandler RvCompleted;
        
        /// <remarks/>
        public event ETL_RvCompletedEventHandler ETL_RvCompleted;
        
        /// <remarks/>
        public event TxCompletedEventHandler TxCompleted;
        
        /// <remarks/>
        public event ETL_TxCompletedEventHandler ETL_TxCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Rv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rv(string sParam) {
            object[] results = this.Invoke("Rv", new object[] {
                        sParam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RvAsync(string sParam) {
            this.RvAsync(sParam, null);
        }
        
        /// <remarks/>
        public void RvAsync(string sParam, object userState) {
            if ((this.RvOperationCompleted == null)) {
                this.RvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRvOperationCompleted);
            }
            this.InvokeAsync("Rv", new object[] {
                        sParam}, this.RvOperationCompleted, userState);
        }
        
        private void OnRvOperationCompleted(object arg) {
            if ((this.RvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RvCompleted(this, new RvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ETL_Rv", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ETL_Rv(string sParam) {
            object[] results = this.Invoke("ETL_Rv", new object[] {
                        sParam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ETL_RvAsync(string sParam) {
            this.ETL_RvAsync(sParam, null);
        }
        
        /// <remarks/>
        public void ETL_RvAsync(string sParam, object userState) {
            if ((this.ETL_RvOperationCompleted == null)) {
                this.ETL_RvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnETL_RvOperationCompleted);
            }
            this.InvokeAsync("ETL_Rv", new object[] {
                        sParam}, this.ETL_RvOperationCompleted, userState);
        }
        
        private void OnETL_RvOperationCompleted(object arg) {
            if ((this.ETL_RvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ETL_RvCompleted(this, new ETL_RvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Tx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Tx(string sParam, string sType) {
            object[] results = this.Invoke("Tx", new object[] {
                        sParam,
                        sType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TxAsync(string sParam, string sType) {
            this.TxAsync(sParam, sType, null);
        }
        
        /// <remarks/>
        public void TxAsync(string sParam, string sType, object userState) {
            if ((this.TxOperationCompleted == null)) {
                this.TxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTxOperationCompleted);
            }
            this.InvokeAsync("Tx", new object[] {
                        sParam,
                        sType}, this.TxOperationCompleted, userState);
        }
        
        private void OnTxOperationCompleted(object arg) {
            if ((this.TxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TxCompleted(this, new TxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ETL_Tx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ETL_Tx(string sParam, string sType) {
            object[] results = this.Invoke("ETL_Tx", new object[] {
                        sParam,
                        sType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ETL_TxAsync(string sParam, string sType) {
            this.ETL_TxAsync(sParam, sType, null);
        }
        
        /// <remarks/>
        public void ETL_TxAsync(string sParam, string sType, object userState) {
            if ((this.ETL_TxOperationCompleted == null)) {
                this.ETL_TxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnETL_TxOperationCompleted);
            }
            this.InvokeAsync("ETL_Tx", new object[] {
                        sParam,
                        sType}, this.ETL_TxOperationCompleted, userState);
        }
        
        private void OnETL_TxOperationCompleted(object arg) {
            if ((this.ETL_TxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ETL_TxCompleted(this, new ETL_TxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RvCompletedEventHandler(object sender, RvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ETL_RvCompletedEventHandler(object sender, ETL_RvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ETL_RvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ETL_RvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TxCompletedEventHandler(object sender, TxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ETL_TxCompletedEventHandler(object sender, ETL_TxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ETL_TxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ETL_TxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591